// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_EOF-1]
	_ = x[_Name-2]
	_ = x[_Literal-3]
	_ = x[_Operator-4]
	_ = x[_AssignOp-5]
	_ = x[_IncOp-6]
	_ = x[_Assign-7]
	_ = x[_Define-8]
	_ = x[_Arrow-9]
	_ = x[_Star-10]
	_ = x[_PipeArrow-11]
	_ = x[_Lparen-12]
	_ = x[_Lbrack-13]
	_ = x[_Lbrace-14]
	_ = x[_Rparen-15]
	_ = x[_Rbrack-16]
	_ = x[_Rbrace-17]
	_ = x[_Comma-18]
	_ = x[_Semi-19]
	_ = x[_Colon-20]
	_ = x[_Dot-21]
	_ = x[_DotDotDot-22]
	_ = x[_Break-23]
	_ = x[_Case-24]
	_ = x[_Chan-25]
	_ = x[_Const-26]
	_ = x[_Continue-27]
	_ = x[_Default-28]
	_ = x[_Defer-29]
	_ = x[_Else-30]
	_ = x[_Fallthrough-31]
	_ = x[_For-32]
	_ = x[_Func-33]
	_ = x[_Go-34]
	_ = x[_Goto-35]
	_ = x[_If-36]
	_ = x[_Import-37]
	_ = x[_Interface-38]
	_ = x[_Map-39]
	_ = x[_Package-40]
	_ = x[_Range-41]
	_ = x[_Return-42]
	_ = x[_Select-43]
	_ = x[_Struct-44]
	_ = x[_Switch-45]
	_ = x[_Type-46]
	_ = x[_Var-47]
	_ = x[tokenCount-48]
}

const _token_name = "EOFnameliteralopop=opop=:=<-*|>([{)]},;:....breakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevar"

var _token_index = [...]uint8{0, 3, 7, 14, 16, 19, 23, 24, 26, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 49, 53, 57, 62, 70, 77, 82, 86, 97, 100, 104, 106, 110, 112, 118, 127, 130, 137, 142, 148, 154, 160, 166, 170, 173, 173}

func (i token) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_token_index)-1 {
		return "token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _token_name[_token_index[idx]:_token_index[idx+1]]
}
